Fastqc@0.1.0
icgc-argo-qc-wg/argo-qc-tools pull request #3
Opened 2021-07-09 21:11 UTC by lindaxiang

2021-07-13 23:20 UTC, junjun-zhang requested changes

2021-07-13 23:20 UTC, junjun-zhang commented on fastqc/main.py
> +def prepare_tarball(seq, qc_metrics, output_dir):
should there be a tar_content.json file to collect information of files in the tar? similar to this: https://github.com/icgc-argo-qc-wg/argo-qc-tools/blob/main/samtools-stats/main.py#L109-L113?

2021-07-16 18:23 UTC, lindaxiang commented on fastqc/pkg.json
> +        "github.com/icgc-argo/data-processing-utility-tools/helper-functions@1.0.1"
right. this tool does not need this helper.

2021-07-16 18:24 UTC, lindaxiang commented on fastqc/main.py
> +    return stdout.strip().split(' ')[-1]
It would be better to standardize the version string across the tools. I remove `v` from the version for now.

2021-07-16 18:25 UTC, lindaxiang commented on fastqc/tests/test-job-1.json
> +    "seq": "input/test_rg_3.bam",
Good point. Add one fastq input test job.

2021-07-16 18:32 UTC, lindaxiang commented on fastqc/main.py
> +def prepare_tarball(seq, qc_metrics, output_dir):
I skip this part as the json file `tar_content.json` will have different `keys` for different tools, which complicates the creation and usage of the json file. 
I feel the idea to have a list of `files_in_tgz` in the song payload is more straightforward. 

![Screen Shot 2021-07-16 at 2 29 29 PM](https://user-images.githubusercontent.com/7522294/125993017-3f8ee0b4-e344-47a2-bec8-aefdbe2064b8.png)

2021-07-20 12:50 UTC, junjun-zhang commented on fastqc/main.py
> +def prepare_tarball(seq, qc_metrics, output_dir):
ok, this can be revisited later

2021-07-20 12:53 UTC, junjun-zhang commented on fastqc/tests/checker.nf
> +    for f in `find . -type f -name "*.txt"`; do
when only compare `*.txt` files? actutally there is no .txt file in the output, effectively no comparison is done.

2021-07-23 12:52 UTC, lindaxiang commented on fastqc/tests/checker.nf
> +    for f in `find . -type f -name "*.txt"`; do
oh, good catch. the `*.txt` file is actually inside the `*.zip` not under the root level. 
the reason of only comparing `*.txt` is that the others are `*.png` and `*.html`, which are generated based on txt file contents. but this is totally for simplification.

2021-09-01 13:41 UTC, RaqManzano commented on fastqc/Dockerfile
> +  && chmod 777 /opt/FastQC/fastqc
I agree, 777 gives access to everyone and can be a security risk.

2021-09-10 14:39 UTC, junjun-zhang approved these changes

2021-09-27 14:51 UTC, merged